# Generated by Django 3.2.5 on 2022-01-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0002_blood_bloodgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodgroup',
            name='group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3, unique=True),
        ),
    ]
