# Generated by Django 3.2.5 on 2022-01-06 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0003_alter_bloodgroup_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_product', to='Frontend.users'),
            preserve_default=False,
        ),
    ]
