# Generated by Django 3.2.5 on 2022-01-06 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0004_product_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('details', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=11)),
                ('image', models.ImageField(upload_to='')),
                ('cost', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ambulance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AmbulanceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('ambulance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambulance_detail', to='Frontend.ambulance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ambulance_order', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
