# Generated by Django 3.2.5 on 2022-01-06 09:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0007_doctor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorappointment',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
