# Generated by Django 3.2.5 on 2022-01-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0008_doctorappointment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminbasicinfo',
            name='websiteSubTitle',
            field=models.CharField(default=1, max_length=255, verbose_name='Website subtitle'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adminbasicinfo',
            name='websiteTile',
            field=models.CharField(default='1', max_length=255, verbose_name='Website tile'),
            preserve_default=False,
        ),
    ]
