# Generated by Django 3.2.5 on 2022-01-06 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0010_rename_websitetile_adminbasicinfo_websitetitle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checkout',
        ),
    ]
