# Generated by Django 3.2.5 on 2022-01-07 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0011_delete_checkout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='admin_token',
        ),
        migrations.RemoveField(
            model_name='users',
            name='admin_username',
        ),
    ]
