# Generated by Django 3.2.5 on 2022-01-07 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0012_auto_20220107_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_verified',
        ),
    ]
